-- Modulo Inspeccion MP (no altera tablas existentes)

CREATE TABLE IF NOT EXISTS defects (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  defect_type ENUM('major','minor') NOT NULL DEFAULT 'minor',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS calibers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS varieties (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  min_score DECIMAL(10,2) NOT NULL,
  max_score DECIMAL(10,2) NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS inspections (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  producer_id BIGINT NOT NULL,
  inspector_id BIGINT NOT NULL,
  inspection_date DATE NOT NULL,
  product VARCHAR(150) NOT NULL,
  is_organic TINYINT(1) NOT NULL DEFAULT 0,
  total_pallets INT NOT NULL,
  created_by BIGINT NOT NULL,
  updated_by BIGINT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_inspections_producer FOREIGN KEY (producer_id) REFERENCES fruta_productor(ID_PRODUCTOR),
  CONSTRAINT fk_inspections_inspector FOREIGN KEY (inspector_id) REFERENCES fruta_inpector(ID_INPECTOR)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS inspection_details (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  inspection_id BIGINT NOT NULL,
  pallet_number VARCHAR(60) NOT NULL,
  sample VARCHAR(120) NOT NULL,
  variety_id INT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_detail_inspection FOREIGN KEY (inspection_id) REFERENCES inspections(id) ON DELETE CASCADE,
  CONSTRAINT fk_detail_variety FOREIGN KEY (variety_id) REFERENCES varieties(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS inspection_measurements (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  inspection_detail_id BIGINT NOT NULL,
  weight DECIMAL(10,2) NOT NULL DEFAULT 0,
  temperature DECIMAL(10,2) NOT NULL DEFAULT 0,
  brix DECIMAL(10,2) NOT NULL DEFAULT 0,
  baxlo DECIMAL(10,2) NOT NULL DEFAULT 0,
  average DECIMAL(10,2) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_measurement_detail FOREIGN KEY (inspection_detail_id) REFERENCES inspection_details(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS inspection_defect_values (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  inspection_detail_id BIGINT NOT NULL,
  defect_id INT NOT NULL,
  value DECIMAL(10,2) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_defect_detail FOREIGN KEY (inspection_detail_id) REFERENCES inspection_details(id) ON DELETE CASCADE,
  CONSTRAINT fk_defect_master FOREIGN KEY (defect_id) REFERENCES defects(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS inspection_caliber_values (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  inspection_detail_id BIGINT NOT NULL,
  caliber_id INT NOT NULL,
  value DECIMAL(10,2) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_caliber_detail FOREIGN KEY (inspection_detail_id) REFERENCES inspection_details(id) ON DELETE CASCADE,
  CONSTRAINT fk_caliber_master FOREIGN KEY (caliber_id) REFERENCES calibers(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS inspection_results (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  inspection_id BIGINT NOT NULL,
  major_defects_sum DECIMAL(10,2) NOT NULL DEFAULT 0,
  minor_defects_sum DECIMAL(10,2) NOT NULL DEFAULT 0,
  score DECIMAL(10,2) NOT NULL DEFAULT 0,
  category_id INT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_result_inspection FOREIGN KEY (inspection_id) REFERENCES inspections(id) ON DELETE CASCADE,
  CONSTRAINT fk_result_category FOREIGN KEY (category_id) REFERENCES categories(id)
) ENGINE=InnoDB;

INSERT INTO categories (name, min_score, max_score, is_active)
SELECT * FROM (
  SELECT 'A' name, 95.00 min_score, 100.00 max_score, 1 is_active
  UNION ALL SELECT 'B', 85.00, 94.99, 1
  UNION ALL SELECT 'C', 0.00, 84.99, 1
) t
WHERE NOT EXISTS (SELECT 1 FROM categories);
