-- Actualización: Ordenes de Proceso (OP)

SET @EXISTE_ID_OPROCESO := (
    SELECT COUNT(*)
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'fruta_proceso'
      AND COLUMN_NAME = 'ID_OPROCESO'
);
SET @SQL_ID_OPROCESO := IF(
    @EXISTE_ID_OPROCESO = 0,
    'ALTER TABLE fruta_proceso ADD COLUMN ID_OPROCESO BIGINT(20) NULL AFTER ID_TPROCESO',
    'SELECT 1'
);
PREPARE stmt_id_oproceso FROM @SQL_ID_OPROCESO;
EXECUTE stmt_id_oproceso;
DEALLOCATE PREPARE stmt_id_oproceso;

CREATE TABLE IF NOT EXISTS exportadora_oproceso (
    ID_OPROCESO BIGINT(20) NOT NULL AUTO_INCREMENT,
    NUMERO_OPROCESO VARCHAR(100) NOT NULL,
    FECHA_TERMINO_ESTIMADA DATE NULL,
    CANTIDAD_CAJA INT NULL,
    OBSERVACION_OPROCESO VARCHAR(500) NULL,
    ID_EMPRESA INT NOT NULL,
    ID_USUARIOI INT NULL,
    ID_USUARIOM INT NULL,
    INGRESO DATETIME NULL,
    MODIFICACION DATETIME NULL,
    ESTADO_REGISTRO TINYINT(1) NOT NULL DEFAULT 1,
    PRIMARY KEY (ID_OPROCESO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS exportadora_oproceso_mercado (
    ID_OPROCESO_MERCADO BIGINT(20) NOT NULL AUTO_INCREMENT,
    ID_OPROCESO BIGINT(20) NOT NULL,
    ID_MERCADO BIGINT(20) NOT NULL,
    PRIMARY KEY (ID_OPROCESO_MERCADO),
    UNIQUE KEY uk_op_mercado (ID_OPROCESO, ID_MERCADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS exportadora_oproceso_productor_variedad (
    ID_OPROCESO_PRODUCTOR_VARIEDAD BIGINT(20) NOT NULL AUTO_INCREMENT,
    ID_OPROCESO BIGINT(20) NOT NULL,
    ID_PRODUCTOR BIGINT(20) NOT NULL,
    ID_VESPECIES BIGINT(20) NOT NULL,
    PRIMARY KEY (ID_OPROCESO_PRODUCTOR_VARIEDAD),
    UNIQUE KEY uk_op_productor_variedad (ID_OPROCESO, ID_PRODUCTOR, ID_VESPECIES)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS exportadora_oproceso_estandar (
    ID_OPROCESO_ESTANDAR BIGINT(20) NOT NULL AUTO_INCREMENT,
    ID_OPROCESO BIGINT(20) NOT NULL,
    ID_ESTANDAR BIGINT(20) NOT NULL,
    PRIMARY KEY (ID_OPROCESO_ESTANDAR),
    UNIQUE KEY uk_op_estandar (ID_OPROCESO, ID_ESTANDAR)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE fruta_proceso
    ADD CONSTRAINT fk_fruta_proceso_oproceso
    FOREIGN KEY (ID_OPROCESO) REFERENCES exportadora_oproceso (ID_OPROCESO)
    ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE exportadora_oproceso_mercado
    ADD CONSTRAINT fk_opmercado_op FOREIGN KEY (ID_OPROCESO) REFERENCES exportadora_oproceso (ID_OPROCESO)
    ON UPDATE CASCADE ON DELETE CASCADE,
    ADD CONSTRAINT fk_opmercado_mercado FOREIGN KEY (ID_MERCADO) REFERENCES fruta_mercado (ID_MERCADO)
    ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE exportadora_oproceso_productor_variedad
    ADD CONSTRAINT fk_opprodvar_op FOREIGN KEY (ID_OPROCESO) REFERENCES exportadora_oproceso (ID_OPROCESO)
    ON UPDATE CASCADE ON DELETE CASCADE,
    ADD CONSTRAINT fk_opprodvar_productor FOREIGN KEY (ID_PRODUCTOR) REFERENCES fruta_productor (ID_PRODUCTOR)
    ON UPDATE CASCADE ON DELETE RESTRICT,
    ADD CONSTRAINT fk_opprodvar_variedad FOREIGN KEY (ID_VESPECIES) REFERENCES fruta_vespecies (ID_VESPECIES)
    ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE exportadora_oproceso_estandar
    ADD CONSTRAINT fk_opestandar_op FOREIGN KEY (ID_OPROCESO) REFERENCES exportadora_oproceso (ID_OPROCESO)
    ON UPDATE CASCADE ON DELETE CASCADE,
    ADD CONSTRAINT fk_opestandar_estandar FOREIGN KEY (ID_ESTANDAR) REFERENCES estandar_eexportacion (ID_ESTANDAR)
    ON UPDATE CASCADE ON DELETE RESTRICT;
